#! /usr/bin/env python

import sys
import install

correctArgs = ['install', 'uninstall', 'h', 'help',]
args = sys.argv

if not len(sys.argv) == 2 or sys.argv[-1] not in correctArgs:
    print install.__doc__

if args[-1] == 'install':
    install.main()

if args[-1] == 'uninstall':
    install.uninstall()

if args[-1] in ['help', 'h']:
    print install.__doc__
