"""
    list of items  used in marking menu, hotkeys, and shelf
"""
# strings to be generated by the install
ICONSPATH = '!MAYA_SHELF!'
HELP_PAGE = '!HELP_PAGE!'

# markingMenu items list
markingMenuItems = [
#==========================#
#       COMPASS MENU       #
#==========================#
    {
        'name':'Combine',
        'subMenu':False,
        'position':'N',
        'command':'import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.combine()',
    },
    {
        'name':'Separate',
        'subMenu':False,
        'position':'NE',
        'command':'import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.faceSeparate()',
    },
    {
        'name':'Symmetry',
        'subMenu':False,
        'position':'NW',
        'command':'import dmptools.tools.symmetry as symmetry;\
            reload(symmetry);symmetry.main()',
    },
    {
        'name':'Split edge',
        'subMenu':False,
        'position':'W',
        'command':'import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.oldSplitEdge()',
    },

#============================#
#       VERTICAL MENU        #
#============================#
    {
        'name':'separator',
        'subMenu':None,
        'position':None,
        'command':None
    },
    {
        'name':'MayaToNuke',
        'subMenu':False,
        'position':False,
        'command':'import dmptools.tools.mayaToNuke.launcher as mtn;\
            mtn.main();import dmptools.setup.markingMenu as mm;mm.deleteMarkingMenu()',
    },
    {
        'name':'Nuke',
        'subMenu':False,
        'position':False,
        'command':'import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.launchNuke();\
            import dmptools.setup.markingMenu as mm;mm.deleteMarkingMenu()',
    },
    {
        'name':'Terminator',
        'subMenu':False,
        'position':False,
        'command':'import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.launchConsole();\
            import dmptools.setup.markingMenu as mm;mm.deleteMarkingMenu()',
    },
    {
        'name':'SublimeText',
        'subMenu':False,
        'position':False,
        'command':'import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.launchSublimeText();\
            import dmptools.setup.markingMenu as mm;mm.deleteMarkingMenu()',
    },
    {
        'name':'newScriptEditor',
        'subMenu':False,
        'position':False,
        'command':'import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.newScriptEditor();\
            import dmptools.setup.markingMenu as mm;mm.deleteMarkingMenu()',
    },
    {
        'name':'ratioCalculator',
        'subMenu':False,
        'position':False,
        'command':'import dmptools.tools.ratioCalculator as ratioCalculator;\
            ratioCalculator.main();\
            import dmptools.setup.markingMenu as mm;mm.deleteMarkingMenu()',
    },
    {
        'name':'Camera Constraint',
        'subMenu':False,
        'position':False,
        'command':'import dmptools.tools.camConstraint as camC;\
            reload(camC);camC.main();\
            import dmptools.setup.markingMenu as mm;mm.deleteMarkingMenu()',
    },
    {
        'name':'Run command',
        'subMenu':False,
        'position':False,
        'command':'import dmptools.tools.runCommand as runCommand;\
            reload(runCommand);runCommand.main(False);\
            import dmptools.setup.markingMenu as mm;mm.deleteMarkingMenu()',
    },
    {
        'name':'Arc System',
        'subMenu':False,
        'position':False,
        'command':'import dmptools.tools.arcSystem as arcSystem;\
            reload(arcSystem);arcSystem.main();\
            import dmptools.setup.markingMenu as mm;mm.deleteMarkingMenu()',
    },
    {
        'name':'Batch Rename',
        'subMenu':False,
        'position':False,
        'command':'import dmptools.tools.batchRename as batchRename;\
            reload(batchRename);batchRename.main(False);\
            import dmptools.setup.markingMenu as mm;mm.deleteMarkingMenu()',
    },
    {
        'name':'UV tile Manager',
        'subMenu':False,
        'position':False,
        'command':'import dmptools.tools.uvManager as uvManager;reload(uvManager);uvManager.main();\
        import dmptools.setup.markingMenu as mm;mm.deleteMarkingMenu()',

    },
    {
        'name':'Replace default persp',
        'subMenu':False,
        'position':False,
        'command':'import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.replaceDefaultPersp();\
            import dmptools.setup.markingMenu as mm;mm.deleteMarkingMenu()',
    },
    {
        'name':'HotkeysList',
        'subMenu':False,
        'position':False,
        'annotation':'Show the hotkeys list window',
        'command':'import dmptools.setup.hotkeys as hotkeys;\
            reload(hotkeys);hotkeys.showHotkeysList(dockable=False);\
            import dmptools.setup.markingMenu as mm;mm.deleteMarkingMenu()',
    },
]

# hotkeys list
hotkeysItems = [
    {
        'name':'dmptoolsMarkingMenu',
        'key':'n',
        'alt':False,
        'ctrl':False,
        'release':True,
        'command':'python("import dmptools.setup.markingMenu as markingMenu;\
            reload(markingMenu);markingMenu.createMenu()");',
        'releaseCommand':'python("import dmptools.setup.markingMenu as markingMenu;\
            reload(markingMenu);markingMenu.deleteMarkingMenu()");',
    },
    {
        'name':'createHotkeys',
        'key':'H',
        'alt':True,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.setup.hotkeys as hotkeys;\
            reload(hotkeys);hotkeys.main()");',
    },
#=========================#
#     MODELING SECTION    #
#=========================#
    {
        'name':'alignUVsUP',
        'key':'up',
        'alt':False,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.modeling as modeling;\
            reload(modeling);modeling.alignUVs(False, False, True, False)");',
    },
    {
        'name':'alignUVsDown',
        'key':'down',
        'alt':False,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.modeling as modeling;\
            reload(modeling);modeling.alignUVs(False, False, True, True)");',
    },
    {
        'name':'alignUVsLeft',
        'key':'left',
        'alt':False,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.modeling as modeling;\
            reload(modeling);modeling.alignUVs(True, True, False, False)");',
    },
    {
        'name':'alignUVsRight',
        'key':'right',
        'alt':False,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.modeling as modeling;\
            reload(modeling);modeling.alignUVs(True, False, False, False)");',
    },
    {
        'name':'createCameraUVProj',
        'key':'P',
        'alt':False,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.modeling as modeling;\
            reload(modeling);modeling.createCameraUVProj()");',
    },
    {
        'name':'softEdgeSelection',
        'key':'N',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.modeling as modeling;\
            reload(modeling);modeling.softEdgeSelection()");',
    },
    {
        'name':'advanceMove',
        'key':'Q',
        'alt':False,
        'ctrl':False,
        'release':True,
        'command':'python("import dmptools.utils.modeling as modeling;\
            reload(modeling);modeling.advanceMove()");',
        'releaseCommand':'python("import dmptools.utils.modeling as modeling;\
            reload(modeling);modeling.advanceMoveRelease()");',
    },
    {
        'name':'advanceMoveMulti',
        'key':'q',
        'alt':False,
        'ctrl':False,
        'release':True,
        'command':'python("import dmptools.utils.modeling as modeling;\
            reload(modeling);modeling.advanceMoveMulti()");',
        'releaseCommand':'python("import dmptools.utils.modeling as modeling;\
            reload(modeling);modeling.advanceMoveRelease()");',
    },
    {
        'name':'advanceMoveMultiExtrude',
        'key':'a',
        'alt':False,
        'ctrl':False,
        'release':True,
        'command':'python("import dmptools.utils.modeling as modeling;\
            reload(modeling);modeling.advanceMoveMultiExtrude()");',
        'releaseCommand':'python("import dmptools.utils.modeling as modeling;\
            reload(modeling);modeling.advanceMoveRelease()");',
    },
    {
        'name':'splitEdge',
        'key':'A',
        'alt':False,
        'ctrl':False,
        'release':True,
        'command':'python("import dmptools.utils.modeling as modeling;\
            reload(modeling);modeling.oldSplitEdge()");',
        'releaseCommand':'python("import dmptools.utils.modeling as modeling;\
            reload(modeling);modeling.advanceMoveRelease()");',
    },
    {
        'name':'splitEdgeRing',
        'key':'A',
        'alt':False,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.modeling as modeling;\
            reload(modeling);modeling.splitEdgeRing()");',
    },
    {
        'name':'mergeVertex',
        'key':'m',
        'alt':False,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.modeling as modeling;\
            reload(modeling);modeling.mergeVertex()");',
    },
    {
        'name':'mergeUVs',
        'key':'X',
        'alt':False,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.modeling as modeling;\
            reload(modeling);modeling.mergeUVs()");',
    },
#=========================#
#     DISPLAY SECTION     #
#=========================#
    {
        'name':'setDefaultRenderer',
        'key':'1',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.setDefaultRenderer()");',
    },
    {
        'name':'setHardwareRenderer',
        'key':'2',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.setHardwareRenderer()");',
    },
    {
        'name':'setViewport2Renderer',
        'key':'3',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.setViewport2Renderer()");',
    },
    {
        'name':'toggleVertexColorDisplay',
        'key':'C',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.toggleVertexColorDisplay()");',
    },

    {
        'name':'setPreviousRenderVersion',
        'key':'[',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools_misc.framestore.maya.fbkUtils as fbkUtils;reload(fbkUtils);fbkUtils.setPreviousVersion(\'render\', True, True)");',
    },
    {
        'name':'setNextRenderVersion',
        'key':']',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools_misc.framestore.maya.fbkUtils as fbkUtils;reload(fbkUtils);fbkUtils.setNextVersion(\'render\', True, True)");',
    },
    {
        'name':'setPreviousRenderDisplayVersion',
        'key':'{',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools_misc.framestore.maya.fbkUtils as fbkUtils;reload(fbkUtils);fbkUtils.setPreviousVersion(\'render\', False, True)");',
    },
    {
        'name':'setNextRenderDisplayVersion',
        'key':'}',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools_misc.framestore.maya.fbkUtils as fbkUtils;reload(fbkUtils);fbkUtils.setNextVersion(\'render\', False, True)");',
    },
    {
        'name':'setLatestVersion',
        'key':']',
        'alt':True,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools_misc.framestore.maya.fbkUtils as fbkUtils;reload(fbkUtils);fbkUtils.setLatestVersion(\'render\', False, False)");',
    },
    {
        'name':'switchFbkResolution',
        'key':'G',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools_misc.framestore.maya.fbkUtils as fbkUtils;\
            reload(fbkUtils);fbkUtils.switchAnimRender()");',
    },
    {
        'name':'toggleNormals',
        'key':'n',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.toggleNormals()");',
    },
    {
        'name':'setWireframe',
        'key':'w',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.setWireframe()");',
    },
    {
        'name':'setBackfaceCulling',
        'key':'B',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.setBackfaceCulling()");',
    },
    {
        'name':'setDefaultMaterial',
        'key':'d',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.setDefaultMaterial()");',
    },
    {
        'name':'switchLight',
        'key':'l',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.switchLight()");',
    },
    {
        'name':'switchHighlightedSelection',
        'key':'f',
        'alt':True,
        'ctrl':False,'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.switchHighlightedSelection()");',
    },
    {
        'name':'cameraPanTool',
        'key':'z',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.cameraPanTool()");',
    },
    {
        'name':'cameraZoomTool',
        'key':'Z',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.cameraZoomTool()");',
    },
    {
        'name':'resetPanZoom',
        'key':'Z',
        'alt':True,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.resetPanZoom()");',
    },
    {
        'name':'isolateSelection',
        'key':'h',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.isolateSelection()");',
    },

#============================#
#       WINDOWS SECTION      #
#============================#
    {
        'name':'namespaceEditor',
        'key':'n',
        'alt':True,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.openNamespaceEditor()");',
    },
    {
        'name':'openNodeEditor',
        'key':'3',
        'alt':True,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.openNodeEditor()");',
    },
    {
        'name':'showHotkeysList',
        'key':'H',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.setup.hotkeys as hotkeys;\
            reload(hotkeys);hotkeys.showHotkeysList()");',
    },
    {
        'name':'openUvTextureEditor',
        'key':'2',
        'alt':True,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.openUvTextureEditor()");',
    },
    {
        'name':'openHypershade',
        'key':'1',
        'alt':True,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.openHypershade()");',
    },
#===========================#
#     SELECTION SECTION     #
#===========================#
    {
        'name':'freezeHistory',
        'key':'F',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.freezeHistory()");',
    },
    {
        'name':'freezeHistoryCenterPivot',
        'key':'F',
        'alt':True,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.freezeCenterPivot()");',
    },
    {
        'name':'centerPivot',
        'key':'F',
        'alt':False,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.centerPivot()");',
    },
    {
        'name':'hideSelectionSwitch',
        'key':'h',
        'alt':False,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.hideSelSwitch()");',
    },
    {
        'name':'invertSelection',
        'key':'I',
        'alt':False,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.invertSelection()");',
    },
    {
        'name':'selectNgones',
        'key':'q',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.switchSelectNgones()");',
    },
    {
        'name':'selectTriangles',
        'key':'p',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.switchSelectTriangles()");',
    },
    {
        'name':'unselectAll',
        'key':'space',
        'alt':False,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.unselectAll()");',
    },
    {
        'name':'shortestEdgePath',
        'key':'Q',
        'alt':True,
        'ctrl':True,
        'release':True,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.shortestEdgePath()");',
        'releaseCommand':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.shortestEdgePathRelease()");',
    },
#============================#
#         MISC SECTION       #
#============================#
    {
        'name':'launchConsole',
        'key':'x',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.launchConsole()");',
    },
    {
        'name':'askFlushUndo',
        'key':'f',
        'alt':False,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.askFlushUndo()");',
    },
    {
        'name':'saveAs',
        'key':'S',
        'alt':False,
        'ctrl':True,
        'release':False,
        'command':'SaveSceneAs;',
    },
    {
        'name':'switchObjectTumble',
        'key':'Q',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.switchObjectTumble()");',
    },
    {
        'name':'runCommand',
        'key':'e',
        'alt':True,
        'ctrl':False,
        'release':False,
        'command':'python("import dmptools.tools.runCommand as runCommand;\
            reload(runCommand);runCommand.main(False)");',
    },
    {
        'name':'setNamespace',
        'key':'N',
        'alt':False,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.setNamespace()");',
    },
    {
        'name':'switchColors',
        'key':'c',
        'alt':True,
        'ctrl':True,
        'release':False,
        'command':'python("import dmptools.utils.mayaCommands as mayaCommands;\
            reload(mayaCommands);mayaCommands.switchColors()");',
    },
]

# shelf buttons list
shelfItems = [
    {
        'name':'dmptools shelf',
        'command':'import dmptools.setup.shelf as shelf;shelf.main()',
        'icon':ICONSPATH+'/refresh.png',
        'annotation':'Rebuild the dmptools shelf - right click for options.',
        'menu':True,
        'menuItems':[
            ('Initialize dmptools', 'import dmptools.setup.init'),
            ('divider2', ''),
            ('Open maya command port', 'import dmptools.setup.mayaSettings as mayaSettings;mayaSettings.openCommandPort()'),
            ('Set Custom Settings', 'import dmptools.setup.mayaSettings as ms;ms.setCustomSettings()'),
            ('Set Default Settings', 'import dmptools.setup.mayaSettings as ms;ms.setDefaultSettings()'),
        ]
    },
    {
        'name':'separator1'
    },
    {
        'name':'Help',
        'command':'print "right click for full list.", ',
        'icon':ICONSPATH+'/hotkeys.png',
        'annotation':'Help associated commands.',
        'menu':True,
        'menuItems':[
            ('Show dmptools shortcuts', 'import dmptools.setup.hotkeys as hotkeys;reload(hotkeys);hotkeys.showHotkeysList(dockable=False)'),
            ('Open dmptools github page','import webbrowser;webbrowser.open("'+HELP_PAGE+'")'),
            ('Open Maya commands page','import webbrowser;webbrowser.open("http://download.autodesk.com/global/docs/maya2014/en_us/CommandsPython/index.html")'),
        ]
    },
    {
        'name':'separator2'
    },
    {
        'name':'Terminator',
        'command':'print "right click for full list.", ',
        'icon':ICONSPATH+'/Console.xpm',
        'annotation':'Launch a Terminal.',
        'menu':True,
        'menuItems':[
            ('Terminal','import dmptools.utils.mayaCommands as mayaCommands;reload(mayaCommands);mayaCommands.launchTerminal()'),
            ('Windows console','import dmptools.utils.mayaCommands as mayaCommands;reload(mayaCommands);mayaCommands.launchConsole()'),
        ]
    },
    {
        'name':'Script/Code Editor',
        'command':'print "right click for full list.", ',
        'icon':'text.png',
        'annotation':'Script/Code Editor.',
        'menu':True,
        'menuItems':[
            ('script editor','import dmptools.utils.mayaCommands as mayaCommands;reload(mayaCommands);mayaCommands.openScriptEditor()'),
            ('charcoal editor','import dmptools.utils.mayaCommands as mayaCommands;reload(mayaCommands);mayaCommands.openCharcoalEditor()'),
            ('Sublime Text','import dmptools.utils.mayaCommands as mayaCommands;reload(mayaCommands);mayaCommands.launchSublimeText()'),
            ('custom script editor','import dmptools.utils.mayaCommands as mayaCommands;reload(mayaCommands);mayaCommands.newScriptEditor()'),
        ]
    },
    {
        'name':'Nuke',
        'command':'print "right click for full list.", ',
        'icon':ICONSPATH+'/Nuke.xpm',
        'annotation':'Launch Nuke.',
        'menu':True,
        'menuItems':[
            ('Launch Nuke','import dmptools.utils.mayaCommands as mayaCommands;reload(mayaCommands);mayaCommands.launchNuke()'),
        ]
    },
# deprecated maya to nuke button. moved to the Utils menu item list
#    {
#        'name':'mayaToNuke',
#        'command':'import dmptools.tools.mayaToNuke.launcher as mayaToNukeLauncher;mayaToNukeLauncher.main(False)',
#        'icon':ICONSPATH+'/MayaToNuke.xpm',
#        'annotation':'Maya to Nuke Exporter.',
#        'menu':True,
#        'menuItems':[
#            ('run dockable', 'import dmptools.tools.mayaToNuke.launcher as mayaToNukeLauncher;mayaToNukeLauncher.main(dockable=True)'),
#            ('run undockable', 'import dmptools.tools.mayaToNuke.launcher as mayaToNukeLauncher;mayaToNukeLauncher.main(dockable=False)')
#        ]
#    },
    {
        'name':'separator3'
    },
    {
        'name':'Utils',
        'command':'print "utils - right click for full list", ',
        'icon':ICONSPATH+'/utils.png',
        'annotation':'utils - right click for full list',
        'menu':True,
        'menuItems':[
            ('maya to nuke', 'import dmptools.tools.mayaToNuke.launcher as mayaToNukeLauncher;mayaToNukeLauncher.main(False)'),
            ('batch rename', 'import dmptools.tools.batchRename as batchRename;batchRename.main(False)'),
            ('arc system', 'import dmptools.tools.arcSystem as arcSystem;arcSystem.main()'),
            ('create rooftops', 'import dmptools.tools.createRooftops as createRooftops;createRooftops.main()'),
            ('run command', 'import dmptools.tools.runCommand as runCommand;runCommand.main(False)'),
            ('ratio calculator', 'import dmptools.tools.ratioCalculator as ratioCalculator;ratioCalculator.main()'),
            ('symmetry tool', 'import dmptools.tools.symmetry as symmetry;symmetry.main()'),
            ('uv tiles manager', 'import dmptools.tools.uvManager as uvManager;uvManager.main()'),
            ('bake udim tiles', 'import dmptools.tools.bakeUdimTiles as bakeUdimTiles;bakeUdimTiles.main()'),
            ('fix clip planes', 'import dmptools.utils.mayaCommands as mayaCommands;mayaCommands.fixClipPlanes()'),
            ('bake camera', 'import dmptools.tools.bakeCamera as bakeCamera;bakeCamera.main()'),
        ]
    },
    {
        'name':'Framestore utils',
        'command':'print "utils - right click for full list", ',
        'icon':ICONSPATH+'/framestore_logo.jpg',
        'annotation':'utils - right click for full list',
        'menu':True,
        'menuItems':[
            ('load fShambles...', 'import dmptools_misc.framestore.maya.jsonWrite as jsonWrite;jsonWrite.loadShambles()'),
            ('write fShambles...', 'import dmptools_misc.framestore.maya.jsonWrite as jsonWrite;jsonWrite.main()'),
            ('divider3', ''),
            ('get fd state', 'import dmptools.utils.mayaCommands as mayaCommands;reload(mayaCommands);mayaCommands.getFdState()'),
            ('get fd list', 'import dmptools.utils.mayaCommands as mayaCommands;reload(mayaCommands);mayaCommands.getLenFd(True)'),
            ('flush fd', 'import dmptools.utils.mayaCommands as mayaCommands;reload(mayaCommands);mayaCommands.flushFd()'),
        ]
    },
    {
        'name':'separator4'
    },
    {
        'name':'custom',
        'command':'import dmptools.setup.customItems as customItems;reload(customItems);customItems.addItem()',
        'icon':ICONSPATH+'/create.png',
        'annotation':'create custom item with associated command - right click for full list',
        'menu':True,
        'menuItems':[
            ('add item', 'import dmptools.setup.customItems as customItems;reload(customItems);customItems.addItem()'),
            ('edit/remove item', 'import dmptools.setup.customItems as customItems;reload(customItems);customItems.editRemoveItemsUI()'),
            ('divider1', ''),
            # that's where the custom items created by the user are going to be placed.
        ]
    },
    {
        'name':'separator5'
    }
  ]
